### PR TITLE
feat(whitelist):  add XenoBunny contracts to whitelist

### PR DESCRIPTION
**Pull request by LaplaceMan**
**Pull Request Template**

---

### Title
feat(whitelist):  add XenoBunny contracts to whitelist
---

### Description
 add XenoBunny contracts to whitelist

#### What does this PR do?

 add XenoBunny contracts to whitelist
---

### Checklist

*Ensure all items are checked before merging.*

- [x] I have followed the conventional commit messages standard.
- [x] Any whitelisted contracts added are verified.

---

### Additional Notes

---

### CODE REVIEW

**Comment by KorbinianK** [comment]
@LaplaceMan please fix the conflicts

**Comment by bennettyong** [comment]
@LaplaceMan please also add your contracts here: https://github.com/taikoxyz/trailblazer-adapters/blob/main/adapters/projects/gaming/whitelist.go#L13

**Comment by LaplaceMan** [comment]
> @LaplaceMan please fix the conflicts

fixed

**Comment by bennettyong** [comment]
> > @LaplaceMan please fix the conflicts
> 
> fixed

tests failing, run `go test ./...` from root to check locally

**Comment by LaplaceMan** [comment]
> > > @LaplaceMan please fix the conflicts
> > 
> > 
> > fixed
> 
> tests failing, run `go test ./...` from root to check locally

done. thanks.

**Review by bennettyong — APPROVED** [review]

**Pull request merged**
