### PR TITLE
dailycheckin to earn reward

### PR DESCRIPTION
**Pull request by fana186**
### **Title**
dailycheckin

### **Description**
The dailycheckin protocol is designed to incentivize user participation through a daily check-in mechanism. Users interact with the smart contract to register their daily presence, and in return, they receive rewards based on their activity. This can be beneficial for various use cases, such as loyalty programs, social engagement platforms, or gamified experiences.

**Features**:
Daily Participation Tracking: Users can check in daily and track their activity over time.
Reward System: Users earn rewards based on their participation, such as points, tokens, or other incentives.
Blockchain-Backed Transparency: All transactions are recorded on the blockchain, ensuring transparency and immutability.
This contract serves as a foundational element for applications aiming to gamify user engagement or create systems that incentivize regular participation. The dailycheckin protocol can be seamlessly integrated with other platforms and smart contracts to provide a smooth and cohesive user experience.

### **What does this PR do?**
This PR adds the dailycheckin protocol to the whitelist in the protocols.json file. Specifically, it registers the contract address 0xB4cc31bFdc8909bf301523265166F3F5ED57eC55 under the dailycheckin protocol, allowing it to be recognized and tracked by the system. This enables the protocol to be included in transaction tracking, rewards distribution, and other related processes within the platform.

By merging this PR, the dailycheckin contract will interact with the platform’s existing functionality, supporting use cases such as daily user check-ins and reward-based systems.

**### Checklist**
Ensure all items are checked before merging.

**Yes** I have followed the conventional commit messages standard.
**yes**   whitelisted contracts added are verified.
### **Additional Notes**
The dailycheckin protocol aims to track daily user participation and reward engagement on the platform. The contract at 0xB4cc31bFdc8909bf301523265166F3F5ED57eC55 has been deployed and tested to ensure it functions as intended.
This PR does not introduce any breaking changes or modifications to other protocols. It only adds the dailycheckin protocol to the whitelist for future transaction tracking.

### CODE REVIEW

**Comment by fana186** [comment]
@myronrotter 
yes 162 was also requested by me now i closed the 162  pull rquest kindly rewiew this as soon as posible

**Comment by fana186** [comment]
> @myronrotter yes 162 was also requested by me now i closed the 162 pull rquest kindly rewiew this as soon as posible

when will team will review this

**Comment by KorbinianK** [comment]
Do not create duplicate PRs. Further this is not a dapp, this is a chatgpt generated contract to farm Trailblazers without any UI. We will not accept this to be whitelisted. Please do not open another PR on this topic.

**Comment by fana186** [comment]
> Do not create duplicate PRs. Further this is not a dapp, this is a chatgpt generated contract to farm Trailblazers without any UI. We will not accept this to be whitelisted. Please do not open another PR on this topic.

if i build a daap with ui .. will you whitelisted this.. my purpose not to to farm trailblazer i just made it for my community.

**Pull request closed without merging**
